FROM python:3.13-slim AS build

ARG VERSION=1.15
ARG BUILD=latest

COPY get-waterfall.py get-waterfall.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN python get-waterfall.py --version $VERSION --build $BUILD --output /endkind/server.jar

FROM eclipse-temurin:11 AS runtime

LABEL Author="Endkind Ender <endkind.ender@endkind.net>"

COPY entrypoint.sh /endkind/entrypoint.sh
COPY --from=build /endkind/server.jar /endkind/server.jar

WORKDIR /data
VOLUME /data

ENV MIN_RAM=32M
ENV MAX_RAM=3G
ENV JAVA_FLAGS="-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
ENV WATERFALL_FLAGS="--nojline"

ENTRYPOINT [ "/endkind/entrypoint.sh" ]
